export default function handler(req, res) {
  res.status(200).json(
    {
      id: 1,
      name: "Suraj Basnet",
      phone: "9812345678",
      email: "surajb11@gmail.com",
      references: "by Babul",
      technology: "ReactJS",
      salaryExpectation: "Above 20000",
      level: "Mid",
      status: "Hired",
      experience: "1 year",
    },
    {
      id: 2,
      name: "Rewan Thapa",
      phone: "9812345879",
      email: "rewanthapa@gmail.com",
      references: "Non User",
      technology: "QA",
      salaryExpectation: "Above 35000",
      level: "Mid",
      status: "Hired",
      experience: "3 year",
    },
    {
      id: 3,
      name: "Ashmita Budathoki",
      phone: "9812455789",
      email: "asmita@gmail.com",
      references: "Non User",
      technology: ".Net",
      salaryExpectation: "Above 40000",
      level: "Mid",
      status: "Hired",
      experience: "4 year",
    },

    {
      id: 3,
      name: "Manoj Basnet",
      phone: "98123456789",
      email: "rewanthapa@gmail.com",
      references: "Non User",
      technology: "DevOps",
      salaryExpectation: "Above 50000",
      level: "Mid",
      status: "Hired",
      experience: "5 year",
    },
    {
      id: 4,
      name: "Sushmita Thapa",
      phone: "9814455771",
      email: "susmita@gmail.com",
      references: "by Sumit Sir",
      technology: "ReactJS",
      salaryExpectation: "Above 20000",
      level: "Junior",
      status: "Rejected",
      experience: "1 year",
    },

    {
      id: 5,
      name: "Yuvish Basnet",
      phone: "9800321756",
      email: "Yuvish@gmail.com",
      references: "Non User",
      technology: ".Net",
      salaryExpectation: "Above 30000",
      level: "Junior",
      status: "BlackListed",
      experience: "1 year",
    },

    {
      id: 6,
      name: "Riyon Shrestha",
      phone: "98123456789",
      email: "riyon@gmail.com",
      references: "Non User",
      technology: "QA",
      salaryExpectation: "Above 45000",
      level: "Junior",
      status: "BlackListed",
      experience: "1 year",
    },
    {
      id: 7,
      name: "Neta Pathak",
      phone: "98001234567",
      email: "neeta@gmail.com",
      references: "by Rakesh Sir",
      technology: "ReactJS",
      salaryExpectation: "Above 7000",
      level: "Junior",
      status: "Rejected",
      experience: "1 year",
    },

    {
      id: 8,
      name: "Dabit Chauhan",
      phone: "9878909876",
      email: "dabit@gmail.com",
      references: "by Sumit Sir",
      technology: "DevOps",
      salaryExpectation: "Above 60000",
      level: "Mid",
      status: "Hired",
      experience: "5 year",
    },
    {
      id: 9,
      name: "Smith Malla",
      phone: "9812665833",
      email: "smit@gmail.com",
      references: "Non User",
      technology: "QA",
      salaryExpectation: "Above 40000",
      level: "Mid",
      status: "Hired",
      experience: "3 year",
    },

    {
      id: 10,
      name: "Kamal Magar",
      phone: "9856123457",
      email: "rkamal2@gmail.com",
      references: "By Nista mam",
      technology: "ReactJS",
      salaryExpectation: "Above 17000",
      level: "Junior",
      status: "Hired",
      experience: "1 year",
    }
  );
}
